### PR TITLE
fix(api): use path.join to create attachment download URLs

### PR DESCRIPTION
**Pull request by mediremi**
Closes https://jira.dhis2.org/browse/DHIS2-9849

### CODE REVIEW

**Review by HendrikThePendric — COMMENTED** [review]
I think using the `path` module probably makes sense here. I've seen this double slash problem before in a few apps, and using the path module would help. However, I think there is a problem with this PR though. I don't see any changes in `package.json` and....
```text
messaging-app on  master is 📦 v31.0.0 via ⬢ v10.22.0 
❯ yarn why path
yarn why v1.22.5
[1/4] 🤔  Why do we have the module "path"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
✨  Done in 0.94s.
```

So I think when we build the app and deploy it, this won't work in it's current state. We'll need to add `path` to the dependencies.

**Review by HendrikThePendric — CHANGES_REQUESTED** [review]
Sorry, I meant to request changes before but had the wrong radio selected.

**Comment by mediremi** [comment]
The reason why this currently builds without the explicit dependency on `path` in `package.json` is that webpack < v5 (we're currently on [v4.44.2](https://github.com/facebook/create-react-app/blob/v4.0.0/packages/react-scripts/package.json#L84) through's `app-platform`'s dependency on `react-scripts`) polyfills some nodejs core modules. In this case, the polyfill is [path-browserify](https://github.com/browserify/path-browserify).

Before I looked into it today, I didn't realise that these [polyfills were deprecated with webpack version 5](https://github.com/webpack/webpack/blob/5573fed586aa3960794e8e4ad39f8766e3de88a4/lib/ModuleNotFoundError.js#L61-L65) so I'll add an explicit dependency on `path-browserify`.

**Comment by amcgee** [comment]
Code LGTM - @HendrikThePendric can you confirm?

**Review by HendrikThePendric — APPROVED** [review]

**Pull request merged**
